import { useEffect, useState } from 'react';
import { Alert, FlatList, Image, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { rupiah } from '../data/mock';
import { getLocalProducts, syncPartnerProducts, updatePartnerProductPrice } from '../products/products-sync';
import { colors } from '../theme';
import { Product, Session } from '../types';

export function InventoryScreen({ session }: { session: Session }) {
  const [items, setItems] = useState<Product[]>([]); const [editing, setEditing] = useState<Product | null>(null); const [price, setPrice] = useState(''); const [saving, setSaving] = useState(false);
  const load = async () => { setItems(await getLocalProducts(session.mitraId)); await syncPartnerProducts(session).catch(() => undefined); setItems(await getLocalProducts(session.mitraId)); };
  useEffect(() => { setEditing(null); void load(); }, [session.accessToken, session.mitraId]);
  const openPrice = (item: Product) => { setEditing(item); setPrice(item.price > 0 ? String(item.price) : ''); };
  const savePrice = async () => { const value = Number(price); if (!editing || !Number.isFinite(value) || value < 0 || !price) return Alert.alert('Harga belum valid', 'Masukkan harga jual produk.'); setSaving(true); try { await updatePartnerProductPrice(session, editing.id, value); setItems((current) => current.map((item) => item.id === editing.id ? { ...item, price: value } : item)); setEditing(null); Alert.alert('Harga tersimpan', 'Harga baru langsung digunakan di halaman Kasir.'); } catch (error) { Alert.alert('Harga gagal disimpan', error instanceof Error ? error.message : 'Terjadi kesalahan'); } finally { setSaving(false); } };
  return <View style={styles.screen}><View style={styles.notice}><Text style={styles.noticeTitle}>Stok Mitra</Text><Text style={styles.noticeText}>Atur harga jual sendiri untuk setiap produk yang diterima dari pusat.</Text></View><FlatList data={items} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={styles.empty}>Belum ada produk dari pusat.</Text>} renderItem={({ item }) => <View style={styles.row}>{item.imageUrl ? <Image source={{ uri: item.imageUrl }} style={styles.art} /> : <View style={[styles.art, { backgroundColor: item.color }]}><Text style={styles.artText}>{item.name[0]}</Text></View>}<View style={styles.info}><Text style={styles.name}>{item.name}</Text><Text style={styles.price}>{item.price > 0 ? rupiah(item.price) : 'Harga belum diatur'}</Text></View><View style={styles.stock}><Text style={styles.stockValue}>{item.stock}</Text><Text style={styles.stockLabel}>stok</Text></View><Pressable onPress={() => openPrice(item)} style={styles.edit}><Text style={styles.editText}>Atur harga</Text></Pressable></View>} /><Modal visible={Boolean(editing)} transparent animationType="fade" onRequestClose={() => setEditing(null)}><View style={styles.backdrop}><View style={styles.modal}><Text style={styles.modalTitle}>Harga jual {editing?.name}</Text><Text style={styles.label}>Harga jual Mitra</Text><TextInput value={price} onChangeText={(value) => setPrice(value.replace(/[^0-9]/g, ''))} keyboardType="number-pad" placeholder="Contoh: 15000" placeholderTextColor="#98A2B3" style={styles.input} /><Text style={styles.hint}>Harga ini khusus milik Mitra dan tidak mengubah harga Gudang Pusat.</Text><View style={styles.actions}><Pressable onPress={() => setEditing(null)} style={styles.cancel}><Text style={styles.cancelText}>Batal</Text></Pressable><Pressable disabled={saving} onPress={() => void savePrice()} style={[styles.save, saving && { opacity: .5 }]}><Text style={styles.saveText}>{saving ? 'Menyimpan...' : 'Simpan harga'}</Text></Pressable></View></View></View></Modal></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.canvas, padding: 16 }, notice: { backgroundColor: colors.primarySoft, padding: 15, borderRadius: 14, marginBottom: 13 }, noticeTitle: { color: colors.primary, fontWeight: '800' }, noticeText: { color: colors.muted, fontSize: 11, marginTop: 3 }, list: { backgroundColor: colors.surface, borderRadius: 16, paddingHorizontal: 14 }, row: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: colors.line }, art: { width: 48, height: 48, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, artText: { color: colors.ink, fontSize: 20, fontWeight: '900' }, info: { flex: 1 }, name: { color: colors.ink, fontWeight: '800' }, price: { color: colors.muted, fontSize: 11, marginTop: 3 }, stock: { minWidth: 38, alignItems: 'center' }, stockValue: { color: colors.ink, fontWeight: '900', fontSize: 16 }, stockLabel: { color: colors.muted, fontSize: 9 }, edit: { paddingHorizontal: 10, paddingVertical: 8, borderRadius: 8, backgroundColor: colors.primarySoft }, editText: { color: colors.primary, fontWeight: '800', fontSize: 9 }, empty: { color: colors.muted, textAlign: 'center', padding: 35 }, backdrop: { flex: 1, backgroundColor: 'rgba(16,24,40,.55)', justifyContent: 'center', padding: 20 }, modal: { width: '100%', maxWidth: 450, alignSelf: 'center', backgroundColor: colors.surface, borderRadius: 18, padding: 18 }, modalTitle: { color: colors.ink, fontSize: 17, fontWeight: '900' }, label: { color: colors.ink, fontWeight: '700', fontSize: 11, marginTop: 14, marginBottom: 6 }, input: { height: 47, borderWidth: 1, borderColor: colors.line, borderRadius: 10, paddingHorizontal: 12, color: colors.ink }, hint: { color: colors.muted, fontSize: 10, marginTop: 8 }, actions: { flexDirection: 'row', gap: 9, marginTop: 18 }, cancel: { flex: 1, padding: 13, borderWidth: 1, borderColor: colors.line, borderRadius: 10, alignItems: 'center' }, cancelText: { color: colors.ink, fontWeight: '800' }, save: { flex: 2, padding: 13, backgroundColor: colors.primary, borderRadius: 10, alignItems: 'center' }, saveText: { color: '#FFF', fontWeight: '800' } });
