import { useEffect, useMemo, useState } from 'react';
import { Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { CartPanel } from '../components/CartPanel';
import { ProductCard } from '../components/ProductCard';
import { recordSale } from '../database/sales.repository';
import { getLocalProducts, syncPartnerProducts } from '../products/products-sync';
import { colors } from '../theme';
import { CartItem, Product, Session } from '../types';

export function PosScreen({ isTablet, session, onTransactionSaved }: { isTablet: boolean; session: Session; onTransactionSaved: () => void }) {
  const [products, setProducts] = useState<Product[]>([]); const [cart, setCart] = useState<CartItem[]>([]);
  const [query, setQuery] = useState(''); const [category, setCategory] = useState('Semua'); const [showCart, setShowCart] = useState(false);
  useEffect(() => { setCart([]); const load = async () => { setProducts(await getLocalProducts(session.mitraId, 'produk_jadi')); await syncPartnerProducts(session).catch(() => undefined); setProducts(await getLocalProducts(session.mitraId, 'produk_jadi')); }; void load(); }, [session.accessToken, session.mitraId]);
  const categories = useMemo(() => ['Semua', ...Array.from(new Set(products.map((item) => item.category)))], [products]);
  const filtered = useMemo(() => products.filter((item) => (category === 'Semua' || item.category === category) && item.name.toLowerCase().includes(query.toLowerCase())), [products, category, query]);
  const itemCount = cart.reduce((sum, item) => sum + item.quantity, 0);
  const add = (product: Product) => setCart((current) => { const found = current.find((item) => item.id === product.id); return found ? current.map((item) => item.id === product.id ? { ...item, quantity: Math.min(item.quantity + 1, item.stock) } : item) : [...current, { ...product, quantity: 1 }]; });
  const changeQuantity = (id: number, delta: number) => setCart((current) => current.map((item) => item.id === id ? { ...item, quantity: Math.min(item.stock, item.quantity + delta) } : item).filter((item) => item.quantity > 0));
  const checkout = async () => { try { for (const item of cart) await recordSale(session.mitraId, item.id, item.quantity, 'Transaksi POS'); setProducts(await getLocalProducts(session.mitraId, 'produk_jadi')); setCart([]); setShowCart(false); onTransactionSaved(); Alert.alert('Transaksi tersimpan', 'Penjualan disimpan ke SQLite dan akan disinkronkan otomatis.'); } catch (error) { Alert.alert('Transaksi gagal', error instanceof Error ? error.message : 'Tidak dapat menyimpan transaksi'); } };
  if (!isTablet && showCart) return <CartPanel items={cart} onChangeQuantity={changeQuantity} onCheckout={() => void checkout()} onBack={() => setShowCart(false)} />;
  return <View style={styles.screen}><View style={styles.catalog}><View style={styles.toolbar}><TextInput value={query} onChangeText={setQuery} placeholder="Cari produk..." placeholderTextColor="#98A2B3" style={styles.search} /></View><View style={styles.categories}>{categories.map((item) => <Pressable key={item} onPress={() => setCategory(item)} style={[styles.chip, category === item && styles.activeChip]}><Text style={[styles.chipText, category === item && styles.activeChipText]}>{item}</Text></Pressable>)}</View><FlatList data={filtered} key={isTablet ? 'tablet' : 'phone'} keyExtractor={(item) => String(item.id)} numColumns={isTablet ? 3 : 2} columnWrapperStyle={styles.gridRow} contentContainerStyle={styles.grid} ListEmptyComponent={<Text style={styles.empty}>Belum ada produk. Hubungkan internet untuk menyinkronkan stok dari pusat.</Text>} renderItem={({ item }) => <ProductCard product={item} onAdd={add} compact={!isTablet} />} />{!isTablet && <Pressable onPress={() => setShowCart(true)} style={styles.floatingCart}><Text style={styles.floatingText}>Lihat keranjang · {itemCount} item</Text></Pressable>}</View>{isTablet && <View style={styles.cartColumn}><CartPanel items={cart} onChangeQuantity={changeQuantity} onCheckout={() => void checkout()} /></View>}</View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, flexDirection: 'row', backgroundColor: colors.canvas }, catalog: { flex: 1 }, cartColumn: { width: '35%', minWidth: 320, maxWidth: 430, borderLeftWidth: 1, borderLeftColor: colors.line }, toolbar: { paddingHorizontal: 16, paddingTop: 15 }, search: { height: 44, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 12, paddingHorizontal: 14, color: colors.ink }, categories: { flexDirection: 'row', gap: 8, paddingHorizontal: 16, paddingVertical: 12, flexWrap: 'wrap' }, chip: { paddingHorizontal: 15, paddingVertical: 8, borderRadius: 999, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line }, activeChip: { backgroundColor: colors.primary, borderColor: colors.primary }, chipText: { color: colors.muted, fontWeight: '700', fontSize: 12 }, activeChipText: { color: '#FFF' }, grid: { paddingHorizontal: 16, paddingBottom: 90 }, gridRow: { gap: 12, marginBottom: 12 }, empty: { color: colors.muted, textAlign: 'center', padding: 30 }, floatingCart: { position: 'absolute', left: 16, right: 16, bottom: 14, backgroundColor: colors.primary, padding: 16, borderRadius: 14, alignItems: 'center' }, floatingText: { color: '#FFF', fontWeight: '800' } });
