import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, FlatList, Image, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { createWarehouseProduct, deleteWarehouseProduct, getWarehouseCatalog, updateWarehouseProduct, uploadWarehouseProductImage, WarehouseProduct } from '../admin/admin-inventory-api';
import { API_URL } from '../config';
import { colors } from '../theme';
import { Session } from '../types';

export function WarehouseManagementScreen({ session }: { session: Session }) {
  const [products, setProducts] = useState<WarehouseProduct[]>([]); const [editingId, setEditingId] = useState<string | null>(null);
  const [name, setName] = useState(''); const [type, setType] = useState(''); const [stock, setStock] = useState(''); const [price, setPrice] = useState('');
  const [image, setImage] = useState<ImagePicker.ImagePickerAsset | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const load = () => { setLoading(true); void getWarehouseCatalog(session).then(setProducts).catch((error) => Alert.alert('Gagal memuat gudang', message(error))).finally(() => setLoading(false)); };
  useEffect(load, [session.accessToken]);
  const reset = () => { setEditingId(null); setName(''); setType(''); setStock(''); setPrice(''); setImage(null); };
  const edit = (item: WarehouseProduct) => { setEditingId(item.id); setName(item.name); setType(item.type); setStock(String(item.stock)); setPrice(String(Number(item.price))); setImage(null); };
  const pick = async () => { try { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], allowsEditing: true, aspect: [1, 1], quality: 0.7 }); const asset = result.canceled ? undefined : result.assets?.[0]; if (asset?.uri) setImage(asset); } catch (error) { Alert.alert('Gambar tidak dapat dipilih', message(error)); } };
  const save = async () => {
    if (name.trim().length < 2 || type.trim().length < 2 || !price.trim()) return Alert.alert('Data belum lengkap', 'Isi nama, tipe, dan harga jual ke Mitra.');
    setSaving(true);
    try {
      const input = { name: name.trim(), type: type.trim(), stock: Number(stock) || 0, price: String(Number(price)) };
      let product = editingId ? await updateWarehouseProduct(session, editingId, input) : await createWarehouseProduct(session, input);
      if (image) product = await uploadWarehouseProductImage(session, product.id, image);
      setProducts((current) => editingId ? current.map((item) => item.id === product.id ? product : item) : [...current, product].sort((a, b) => a.name.localeCompare(b.name)));
      Alert.alert('Produk tersimpan', `${product.name} berhasil disimpan.`); reset();
    } catch (error) { Alert.alert('Gagal menyimpan produk', message(error)); } finally { setSaving(false); }
  };
  const remove = async (item: WarehouseProduct) => { try { await deleteWarehouseProduct(session, item.id); setProducts((current) => current.filter((product) => product.id !== item.id)); if (editingId === item.id) reset(); } catch (error) { Alert.alert('Produk tidak dapat dihapus', message(error)); } };
  const confirmDelete = (item: WarehouseProduct) => Alert.alert('Hapus produk?', `${item.name} akan dihapus dari gudang pusat.`, [{ text: 'Batal', style: 'cancel' }, { text: 'Hapus', style: 'destructive', onPress: () => void remove(item) }]);
  return <View style={styles.screen}><View style={styles.form}><View style={styles.formHeader}><View><Text style={styles.title}>{editingId ? 'Edit produk pusat' : 'Tambah produk pusat'}</Text><Text style={styles.caption}>Gambar dan harga akan tampil pada katalog Mitra.</Text></View>{editingId && <Pressable onPress={reset} style={styles.cancelEdit}><Text style={styles.cancelEditText}>Batal edit</Text></Pressable>}</View><View style={styles.fields}><TextInput value={name} onChangeText={setName} placeholder="Nama produk" placeholderTextColor="#98A2B3" style={[styles.input, styles.grow]} /><TextInput value={type} onChangeText={setType} placeholder="Tipe/kategori" placeholderTextColor="#98A2B3" style={[styles.input, styles.grow]} /><TextInput value={stock} onChangeText={(value) => setStock(digits(value))} keyboardType="number-pad" placeholder="Stok" placeholderTextColor="#98A2B3" style={[styles.input, styles.qty]} /><TextInput value={price} onChangeText={(value) => setPrice(digits(value))} keyboardType="number-pad" placeholder="Harga ke Mitra" placeholderTextColor="#98A2B3" style={[styles.input, styles.priceInput]} /><Pressable onPress={() => void pick()} style={styles.imageButton}><Text style={styles.imageButtonText}>{image ? 'Ganti gambar' : 'Pilih gambar'}</Text></Pressable><Pressable disabled={saving} onPress={() => void save()} style={[styles.button, saving && { opacity: .5 }]}><Text style={styles.buttonText}>{saving ? 'Menyimpan...' : editingId ? 'Simpan perubahan' : 'Tambah'}</Text></Pressable></View>{image && <Image source={{ uri: image.uri }} style={styles.preview} />}</View>{loading ? <ActivityIndicator style={{ marginTop: 30 }} color={colors.primary} /> : <FlatList data={products} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={styles.empty}>Belum ada produk gudang.</Text>} renderItem={({ item }) => <View style={styles.row}>{item.imageUrl ? <Image source={{ uri: imageUri(item.imageUrl) }} style={styles.thumbnail} /> : <View style={styles.placeholder}><Text style={styles.placeholderText}>{item.name[0]}</Text></View>}<View style={styles.info}><Text style={styles.name}>{item.name}</Text><Text style={styles.meta}>{item.type} · Rp{Number(item.price).toLocaleString('id-ID')}</Text></View><Text style={styles.stock}>{item.stock} stok</Text><Pressable onPress={() => edit(item)} style={styles.edit}><Text style={styles.editText}>Edit</Text></Pressable><Pressable onPress={() => confirmDelete(item)} style={styles.remove}><Text style={styles.removeText}>Hapus</Text></Pressable></View>} />}</View>;
}
const digits = (value: string) => value.replace(/[^0-9]/g, ''); const message = (error: unknown) => error instanceof Error ? error.message : 'Terjadi kesalahan'; const imageUri = (path: string) => `${API_URL.replace(/\/api\/v1\/?$/, '')}${path}`;
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.canvas, padding: 16 }, form: { backgroundColor: colors.surface, borderRadius: 16, padding: 16 }, formHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, title: { color: colors.ink, fontSize: 18, fontWeight: '900' }, caption: { color: colors.muted, fontSize: 11, marginTop: 4 }, cancelEdit: { padding: 9, backgroundColor: colors.orangeSoft, borderRadius: 9 }, cancelEditText: { color: colors.orange, fontWeight: '800', fontSize: 10 }, fields: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 14 }, input: { height: 44, borderWidth: 1, borderColor: colors.line, borderRadius: 10, paddingHorizontal: 12, color: colors.ink, backgroundColor: '#FAFAFA' }, grow: { flexGrow: 1, minWidth: 150 }, qty: { width: 90 }, priceInput: { width: 145 }, imageButton: { minHeight: 44, paddingHorizontal: 14, borderWidth: 1, borderColor: colors.primary, borderRadius: 10, justifyContent: 'center' }, imageButtonText: { color: colors.primary, fontWeight: '800', fontSize: 11 }, button: { minHeight: 44, paddingHorizontal: 18, backgroundColor: colors.primary, borderRadius: 10, justifyContent: 'center' }, buttonText: { color: '#FFF', fontWeight: '800' }, preview: { width: 90, height: 90, borderRadius: 12, marginTop: 12 }, list: { backgroundColor: colors.surface, borderRadius: 16, paddingHorizontal: 15, marginTop: 14 }, row: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: colors.line }, thumbnail: { width: 48, height: 48, borderRadius: 10 }, placeholder: { width: 48, height: 48, borderRadius: 10, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, placeholderText: { color: colors.primary, fontWeight: '900', fontSize: 18 }, info: { flex: 1 }, name: { color: colors.ink, fontWeight: '800' }, meta: { color: colors.muted, fontSize: 10, marginTop: 3 }, stock: { color: colors.primary, fontWeight: '900' }, edit: { padding: 8, backgroundColor: colors.primarySoft, borderRadius: 8 }, editText: { color: colors.primary, fontWeight: '800', fontSize: 10 }, remove: { padding: 8, backgroundColor: '#FFF1F0', borderRadius: 8 }, removeText: { color: colors.red, fontWeight: '800', fontSize: 10 }, empty: { color: colors.muted, textAlign: 'center', padding: 30 } });
