import { useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { createPartnerFinishedProduct, deletePartnerFinishedProduct, getAdminWarehouseCatalog, PartnerProductStock, updatePartnerFinishedProduct, WarehouseProduct } from '../admin/admin-inventory-api';
import { colors } from '../theme';
import { Session } from '../types';
import { WarehouseProductPicker } from './WarehouseProductPicker';

export function PartnerProductManager({ session, partnerId, products, onReload }: { session: Session; partnerId: string; products: PartnerProductStock[]; onReload: () => Promise<void> }) {
  const [tab, setTab] = useState<'bahan_baku' | 'produk_jadi'>('produk_jadi');
  const [catalog, setCatalog] = useState<WarehouseProduct[]>([]); const [selected, setSelected] = useState<WarehouseProduct | null>(null); const [editing, setEditing] = useState<PartnerProductStock | null>(null); const [stock, setStock] = useState(''); const [saving, setSaving] = useState(false);
  const visible = useMemo(() => products.filter((item) => item.kind === tab), [products, tab]);
  useEffect(() => { void getAdminWarehouseCatalog(session).then((items) => setCatalog(items.filter((item) => item.kind === 'produk_jadi'))).catch(() => setCatalog([])); }, [session.accessToken]);
  const reset = () => { setSelected(null); setEditing(null); setStock(''); };
  const beginEdit = (item: PartnerProductStock) => { setEditing(item); setSelected(null); setStock(String(item.stock)); };
  const save = async () => {
    const quantity = Number(stock); if ((editing && (!Number.isInteger(quantity) || quantity < 0)) || (!editing && !selected)) return Alert.alert('Data belum valid', 'Pilih produk jadi dengan benar.');
    setSaving(true);
    try { if (editing) await updatePartnerFinishedProduct(session, partnerId, editing.id, { stock: quantity }); else await createPartnerFinishedProduct(session, partnerId, { warehouseId: selected!.id }); reset(); await onReload(); }
    catch (error) { Alert.alert('Produk jadi gagal disimpan', error instanceof Error ? error.message : 'Terjadi kesalahan'); }
    finally { setSaving(false); }
  };
  const remove = (item: PartnerProductStock) => Alert.alert('Hapus produk jadi?', `${item.name} akan dikembalikan ke stok pusat.`, [{ text: 'Batal', style: 'cancel' }, { text: 'Hapus', style: 'destructive', onPress: async () => { try { await deletePartnerFinishedProduct(session, partnerId, item.id); if (editing?.id === item.id) reset(); await onReload(); } catch (error) { Alert.alert('Produk tidak dapat dihapus', error instanceof Error ? error.message : 'Terjadi kesalahan'); } } }]);
  const assignedMasterIds = products.filter((item) => item.kind === 'produk_jadi').map((item) => item.masterId).filter(Boolean);
  const available = catalog.filter((item) => !assignedMasterIds.includes(item.id));
  return <View>
    <View style={styles.tabs}><Tab label="Bahan Baku" active={tab === 'bahan_baku'} onPress={() => setTab('bahan_baku')} /><Tab label="Produk Jadi" active={tab === 'produk_jadi'} onPress={() => setTab('produk_jadi')} /></View>
    {tab === 'produk_jadi' && <View style={styles.form}><Text style={styles.formTitle}>Tambahkan produk jadi ke Mitra</Text><WarehouseProductPicker products={available} selectedIds={selected ? [selected.id] : []} onSelect={setSelected} />{selected && <View style={styles.selected}><Text style={styles.selectedName}>{selected.name}</Text><Text style={styles.selectedMeta}>{selected.type} · {selected.recipes?.length || 0} bahan dalam resep</Text></View>}<View style={styles.formActions}>{selected && <Pressable onPress={reset} style={styles.cancel}><Text style={styles.cancelText}>Batal</Text></Pressable>}<Pressable disabled={saving || !selected} onPress={() => void save()} style={[styles.save, (saving || !selected) && { opacity: .5 }]}><Text style={styles.saveText}>{saving ? 'Menyimpan...' : 'Tambahkan produk'}</Text></Pressable></View></View>}
    {!visible.length ? <Text style={styles.empty}>{tab === 'produk_jadi' ? 'Belum ada produk jadi pada Mitra ini.' : 'Mitra ini belum memiliki bahan baku.'}</Text> : visible.map((product) => <View key={product.id} style={styles.row}><View style={styles.info}><Text style={styles.name}>{product.name}</Text><Text style={styles.meta}>{product.category}{product.kind === 'produk_jadi' ? ` · kapasitas ${product.stock}` : ' · hanya lihat'}</Text></View><Text style={styles.stock}>{product.stock} {product.kind === 'produk_jadi' ? 'bisa dibuat' : 'stok'}</Text>{product.kind === 'produk_jadi' && <Pressable onPress={() => remove(product)} style={styles.remove}><Text style={styles.removeText}>Hapus</Text></Pressable>}</View>)}
  </View>;
}

function Tab({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={[styles.tab, active && styles.activeTab]}><Text style={[styles.tabText, active && styles.activeTabText]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ tabs: { flexDirection: 'row', backgroundColor: colors.canvas, padding: 4, borderRadius: 11, marginBottom: 12 }, tab: { flex: 1, padding: 9, borderRadius: 8, alignItems: 'center' }, activeTab: { backgroundColor: colors.primary }, tabText: { color: colors.muted, fontSize: 10, fontWeight: '800' }, activeTabText: { color: '#FFF' }, form: { padding: 12, borderWidth: 1, borderColor: colors.line, borderRadius: 12, marginBottom: 10 }, formTitle: { color: colors.ink, fontWeight: '900', fontSize: 12 }, selected: { backgroundColor: colors.primarySoft, borderRadius: 9, padding: 10, marginTop: 9 }, selectedName: { color: colors.primary, fontWeight: '900', fontSize: 11 }, selectedMeta: { color: colors.muted, fontSize: 9, marginTop: 3 }, input: { height: 41, borderWidth: 1, borderColor: colors.line, borderRadius: 8, paddingHorizontal: 9, color: colors.ink, fontSize: 11, marginTop: 9 }, formActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 7, marginTop: 8 }, cancel: { padding: 9, borderRadius: 8, backgroundColor: colors.canvas }, cancelText: { color: colors.muted, fontWeight: '800', fontSize: 9 }, save: { paddingHorizontal: 12, paddingVertical: 9, borderRadius: 8, backgroundColor: colors.primary }, saveText: { color: '#FFF', fontWeight: '800', fontSize: 9 }, row: { flexDirection: 'row', alignItems: 'center', gap: 7, paddingVertical: 11, borderBottomWidth: 1, borderBottomColor: colors.line }, info: { flex: 1 }, name: { color: colors.ink, fontWeight: '800', fontSize: 12 }, meta: { color: colors.muted, fontSize: 9, marginTop: 3 }, stock: { color: colors.ink, fontWeight: '900', fontSize: 11 }, edit: { padding: 7, borderRadius: 7, backgroundColor: colors.primarySoft }, editText: { color: colors.primary, fontWeight: '800', fontSize: 9 }, remove: { padding: 7, borderRadius: 7, backgroundColor: '#FFF1F0' }, removeText: { color: colors.red, fontWeight: '800', fontSize: 9 }, empty: { color: colors.muted, textAlign: 'center', paddingVertical: 25, fontSize: 11 } });
